---
-
    name: Generate token for snapshot promote
    set_fact:
      snapshot_token="BASE_TOKEN-{{ ansible_date_time.epoch }}"
    tags:
      - promote-snapshots
      - promote2

-
    name: Create publish snapshots
    shell: >
        (aptly snapshot list -raw | grep -q "{{ item }}" )
        || (aptly snapshot create "{{ item }}" empty )
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    register: register_snapshot_publish
    changed_when: "'successfully created' in register_snapshot_publish.stdout"
    with_items: aptly_snapshot_published
    tags:
      - promote-snapshots

-
    name: Prepare snapshot bases for promote
    shell: >
     aptly snapshot merge "${BASE}-{{ snapshot_token }}" "${BASE}"
    environment:
      BASE: '{{ (aptly_snapshot_promote_definitions | selectattr("name", "equalto", item) | list)[0].base | mandatory }}'
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    changed_when: false
    with_items: aptly_snapshot_promote
    tags:
      - promote-snapshots

-
    name: Unpublish promoting snapshots
    shell: >
        (aptly publish list | grep -q "${NAME}")
        && aptly publish drop "{{ aptly_distribution }}" "{{ aptly_endopoint_config }}{{ item }}" || exit 0
    when: item.0 != None
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    with_items: aptly_snapshot_promote
    tags:
      - promote-snapshots
      - unpublish-snapshots
-
    name: Promote snapshot from bases
    shell: >
        aptly -force=true snapshot drop "{{ item }}"  &&
        aptly snapshot merge "{{ item }}" "${BASE}-{{ snapshot_token }}"
    environment:
      BASE: '{{ (aptly_snapshot_promote_definitions | selectattr("name", "equalto", item) | list)[0].base | mandatory }}'
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    changed_when: false
    with_items: aptly_snapshot_promote
    tags:
      - promote-snapshots
-
    name: Wipe temporary base snapshots
    shell: aptly snapshot list -raw | grep "BASE_TOKEN-" | xargs -I{} aptly -force=true snapshot drop "{}"
    changed_when: false
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    tags:
      - promote-snapshots
-
    name: Publish promoted snapshots
    shell: >
     aptly -distribution="{{ aptly_distribution }}" -skip-contents publish snapshot --architectures "amd64" \
      "{{ item }}" "{{ aptly_endopoint_config }}{{ item }}"
    when: item.0 != None
    sudo: yes
    sudo_user: "{{ aptly_user }}"
    changed_when: false
    with_items: aptly_snapshot_promote
    tags:
      - promote-snapshots